# buildah bud -t fedora-toolbox-ikke:42 Containerfile-f42
FROM registry.fedoraproject.org/fedora-toolbox:42

RUN dnf -y install \
    https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm \
    https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm && \
  dnf copr enable atim/lazygit -y && \
  dnf remove -y xdg-open && \
  dnf install --setopt=install_weak_deps=False -y \
    ImageMagick \
    ImageMagick-heic \
    ack \
    bat \
    btop \
    fd-find \
    feh \
    ffmpeg \
    ffmpeg-libs \
    flatpak \
    flatpak-xdg-utils \
    fzf \
    gcc-c++ \
    git \
    gpicview \
    htop \
    jq \
    jhead \
    lazygit \
    libavdevice \
    libheif-tools \
    libusb1-devel \
    libva-utils \
    lshw \
    make \
    mosh \
    neovim \
    nmap \
    npm \
    powerline-fonts \
    python3-cryptography \
    python3-pip \
    python3-kubernetes \
    ripgrep \
    ruby \
    sshuttle \
    syntastic \
    tig \
    tmux \
    tmux-powerline \
    unrar \
    unzip \
    vim-command-t \
    vim-enhanced \
    vim-jedi \
    vim-powerline \
    wireguard-tools \
    wl-clipboard \
    x264 \
    xclip \
    zsh && \
  dnf update -y && \
  dnf clean all

